# Generated by Django 4.2.2 on 2023-06-15 16:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('rider', 'RIDER'), ('horse', 'HORSE')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('article_type', models.CharField(choices=[('t-shirt', 'T-SHIRT'), ('boots', 'BOOTS'), ('breeches', 'BREECHES'), ('gloves', 'GLOVES')], max_length=15)),
                ('size', models.CharField(choices=[('small', 'S'), ('medium', 'MEDIUM'), ('large', 'LARGE')], max_length=15)),
                ('color', models.CharField(choices=[('black', 'BLACK'), ('white', 'WHITE'), ('grey', 'GREY'), ('blue', 'BLUE')], max_length=15)),
                ('image', models.ImageField(upload_to='art_images')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
