# Generated by Django 4.2.2 on 2023-06-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('t-shirt', 'T-SHIRT'), ('boots', 'BOOTS'), ('breeches', 'BREECHES'), ('gloves', 'GLOVES'), ('saddle cloth', 'SADDLE CLOTH'), ('bridle', 'BRIDLE')], max_length=15),
        ),
        migrations.AlterField(
            model_name='article',
            name='size',
            field=models.CharField(choices=[('small', 'S'), ('medium', 'M'), ('large', 'L')], max_length=15),
        ),
    ]
